### PR TITLE
Fix auth token handing in GitHub Actions

### LINKED ISSUE #257: "Couldn't find a repository matching this job" in GitHub Actions since v1.3.5
I've been trying for a while to upgrade sbt-coveralls from v1.3.2 to a newer version on my projects, but even after you fixed multiple issues affecting me (such as #224 and #250), I'm still unable to upload coverage data from GitHub Actions.

Taking https://github.com/ruippeixotog/akka-testkit-specs2 as an example, using v1.3.2 [works well](https://github.com/ruippeixotog/akka-testkit-specs2/actions/runs/4780777500/jobs/8498719958) (see "Upload coverage data to Coveralls" step). v1.3.3 and v.1.3.4 suffer from unrelated issues so I can't test them, but I could confirm that v1.3.5 [doesn't work](https://github.com/ruippeixotog/akka-testkit-specs2/actions/runs/4780807957/jobs/8498767464). The latest version v1.3.8 behaves [the same way](https://github.com/ruippeixotog/akka-testkit-specs2/actions/runs/4780561113/jobs/8498380968).

I tried with both pull requests and push CI triggers, so this doesn't seem to be due to the behavior of actions/checkout explained in the README. I tried searching through the commits, but https://github.com/scoverage/sbt-coveralls/commit/547ad2a9f456d67805b5e141161c3cd5a154e1b8 changed too many things. Do you have any idea what might be happening?

### PR DESCRIPTION
**Pull request by ruippeixotog**
Fixes #257. See discussion in the issue for context.

The solution to support both the old behavior and the buggy one introduced in #212 ended up becoming more difficult than expected. When someone passes only `COVERALLS_REPO_TOKEN`, it's not possible in general to know if the token passed was a CI service token (old sbt-coveralls behavior for GitHub Actions) or a Coveralls token (forced by the above PR) without asking the user to change some of their settings, which would end up being another breaking change.

In the end, I leveraged the fact that GitHub tokens [have identifiable prefixes](https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/#identifiable-prefixes) to support both cases.

Tested this by publishing a snapshot of sbt-coveralls, [using it with PureConfig](https://github.com/pureconfig/pureconfig/commit/86e31673396850a880597741740fcd0a4dace6fa), confirming that GitHub CI jobs [were successful](https://github.com/pureconfig/pureconfig/actions/runs/5720305068) and checking [Coveralls results](https://coveralls.io/builds/61689161).

### CODE REVIEW

**Comment by ruippeixotog** [comment]
Thanks @rolandtritsch. Like in #266, I think some of the tests in sample projects are flaky and affecting this plugin (there's no reason why sbt-coveralls would cause an assertion on an Akka message to start failing).

**Comment by rolandtritsch** [comment]
Hi @ruippeixotog. Merged it and made it work/pass. Do you want me to cut a release?

**Comment by ruippeixotog** [comment]
That would be great, so we can finally upgrade from 1.3.2. Thanks!

**Comment by rolandtritsch** [comment]
Done. - https://github.com/scoverage/sbt-coveralls/releases/tag/v1.3.10

File: src/main/scala/org/scoverage/coveralls/CoverallPayloadWriter.scala [hunk 1]
```diff
@@ -31,8 +31,16 @@ class CoverallPayloadWriter(
     def writeOpt(fieldName: String, holder: Option[String]) =
       holder foreach { gen.writeStringField(fieldName, _) }
 
-    writeOpt("repo_token", repoToken)
-    writeOpt("service_name", service.map(_.name))
+    coverallsAuth match {
+      case CoverallsRepoToken(token) =>
+        gen.writeStringField("repo_token", token)
```
Comment (mwz) [inline src/main/scala/org/scoverage/coveralls/CoverallPayloadWriter.scala:36]: it appears that `service_name` was missed out in this case, which causes the upload job to fail for private repositories where the coveralls repo token is used:
>Uploading to https://coveralls.io/ failed: Provided service_job_id but not service_name.

**Comment by rolandtritsch** [comment]
This should be fixed now (again) - https://github.com/scoverage/sbt-coveralls/releases/tag/v1.3.13
