### PR TITLE
Fixed gihub actions upload #211

### LINKED ISSUE #211: Upload fails for Github actions (pull request) build
When using github actions build and on **Pull Request** the following error appear:
```bash
[info] Uploading the coveralls file (coveralls.json)
[error] java.lang.RuntimeException: 
[error] Uploading to https://coveralls.io/ failed: Couldn't find a repository matching this job.
[error] The error message 'Couldn't find a repository matching this job' can mean your repo token is incorrect.
```

Notes:
- using the **same coveralls repo token** it works locally with manual upload for my branch
- it also works on Guthub actions with this `sbt` setting:
```sbt
coverallsService := None
```

### PR DESCRIPTION
**Pull request by viktor-podzigun**
It fixes #211 issue, so coverage is uploaded and correctly reported:

Screenshot 2022-11-09 at 10 52 56

### CODE REVIEW

File: src/main/scala/org/scoverage/coveralls/CIService.scala [hunk 1]
```diff
@@ -25,18 +25,22 @@ case object TravisPro extends CIService {
 }
 
 case object GitHubActions extends CIService {
-  val name = "github"
+  val name = ""
```
Comment (viktor-podzigun) [inline src/main/scala/org/scoverage/coveralls/CIService.scala:28]: Apparently, that was the reason it was failing. Idk, maybe in case of `gihub actions` some more params are required by coveralls.io api.

**Comment by viktor-podzigun** [comment]
@rolandtritsch thank you for reviewing and merging it!

Would it be possible to publish new version any time soon?

**Comment by rolandtritsch** [comment]
Hi @viktor-podzigun. Yes. Will to so over the weekend.

**Comment by rolandtritsch** [comment]
Hi @viktor-podzigun. Sorry. It took me a while to get this done. - https://github.com/scoverage/sbt-coveralls/releases/tag/v1.3.3

File: src/main/scala/org/scoverage/coveralls/CIService.scala (hunk 1 above)
Comment (ruippeixotog) [reply src/main/scala/org/scoverage/coveralls/CIService.scala:28]: No, params are fine - it's failing because when the service is "github" you need to pass a GitHub token, not a token obtained in Coveralls pages.

Comment (viktor-podzigun) [reply src/main/scala/org/scoverage/coveralls/CIService.scala:28]: Ah, that makes sense, good catch!
